// spa-testing-demo/angular-testing-demo/src/app/components/async-message-fetcher/async-message-fetcher.component.ts
// src/app/components/async-message-fetcher/async-message-fetcher.component.ts

import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { CommonModule } from '@angular/common'; // <-- KROK 1: ZAIMPORTUJ

@Component({
  selector: 'app-async-message-fetcher',
  standalone: true, // <-- Upewnij się, że to tu jest
  imports: [
    CommonModule // <-- KROK 2: DODAJ DO TABLICY `imports`
  ],
  templateUrl: './async-message-fetcher.component.html',
})
export class AsyncMessageFetcherComponent {
  public message?: string;
  public error?: string;

  constructor(private http: HttpClient) {}

  fetchMessage() {
    this.message = undefined;
    this.error = undefined;
    this.http.get<any>('https://jsonplaceholder.typicode.com/todos/1').subscribe({
      next: (data) => this.message = data.title,
      error: () => this.error = 'Nie udało się pobrać wiadomości',
    });
  }
}
<div>
  <button (click)="fetchMessage()">Pobierz wiadomość</button>
  <p *ngIf="message" data-testid="message-display">{{ message }}</p>
  <p *ngIf="error" role="alert">{{ error }}</p>
</div>

// spa-testing-demo/vue-testing-demo/src/components/AsyncMessageFetcher.vue
<script setup>
import { ref } from 'vue';
const message = ref('');
const error = ref('');
const fetchMessage = async () => {
  message.value = '';
  error.value = '';
  try {
    const res = await fetch('https://jsonplaceholder.typicode.com/todos/1');
    const data = await res.json();
    message.value = data.title;
  } catch (e) {
    error.value = 'Nie udało się pobrać wiadomości';
  }
};
</script>
<template>
  <div>
    <button @click="fetchMessage">Pobierz wiadomość</button>
    <p v-if="message" data-testid="message-display">{{ message }}</p>
    <p v-if="error" role="alert">{{ error }}</p>
  </div>
</template>
