// spa-testing-demo/react-testing-demo/src/components/AsyncMessageFetcher.js
import React, { useState } from 'react';
export function AsyncMessageFetcher() {
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const fetchMessage = () => {
    setMessage('');
    setError('');
    fetch('https://jsonplaceholder.typicode.com/todos/1')
      .then(res => res.json())
      .then(data => setMessage(data.title))
      .catch(() => setError('Nie udało się pobrać wiadomości'));
  };
  return (
    <div>
      <button onClick={fetchMessage}>Pobierz wiadomość</button>
      {message && <p data-testid="message-display">{message}</p>}
      {error && <p role="alert">{error}</p>}
    </div>
  );
}

// spa-testing-demo/vue-testing-demo/src/components/AsyncMessageFetcher.vue
<script setup>
import { ref } from 'vue';
const message = ref('');
const error = ref('');
const fetchMessage = async () => {
  message.value = '';
  error.value = '';
  try {
    const res = await fetch('https://jsonplaceholder.typicode.com/todos/1');
    const data = await res.json();
    message.value = data.title;
  } catch (e) {
    error.value = 'Nie udało się pobrać wiadomości';
  }
};
</script>
<template>
  <div>
    <button @click="fetchMessage">Pobierz wiadomość</button>
    <p v-if="message" data-testid="message-display">{{ message }}</p>
    <p v-if="error" role="alert">{{ error }}</p>
  </div>
</template>
