// spa-testing-demo/vue-testing-demo/src/App.vue
<script setup>
import Greeter from './components/Greeter.vue';
import Counter from './components/Counter.vue';
import AsyncMessageFetcher from './components/AsyncMessageFetcher.vue';
</script>
<template>
  <header>
    <Greeter name="Studencie" />
    <hr />
    <Counter />
    <hr />
    <AsyncMessageFetcher />
  </header>
</template>

// spa-testing-demo/react-testing-demo/src/App.js
import { Counter } from './components/Counter';
import { Greeter } from './components/Greeter';
import { AsyncMessageFetcher } from './components/AsyncMessageFetcher';
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <Greeter name="Studencie" />
        <hr />
        <Counter />
        <hr />
        <AsyncMessageFetcher />
      </header>
    </div>
  );
}
export default App;
